name: Terraform Delete instance Workflow

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Name of the ec2 instance to delete'
        required: true

env:
  TF_VAR_instance_name: ${{ github.event.inputs.instance_name }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init
        working-directory: ec2_module

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ec2_module
